
####

GET http://localhost:8000/api/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIwMTk5NjFhMS1lZjc2LTcwZTYtYWQ1Ny1lY2NkOGU0MjlhZjYiLCJqdG
kiOiJiMzcxYjAyNjkxM2E1NjAzOTU1ZTM4NzY2NWU1YmE0ZTE4OTg4YzAxNGIyY2FjNzBiMzNjNTAwYTM4YmYyNDgwMmUwMjM0ZDFkYzQ5NTU3OSIsImlhdCI6
MTc1ODI5MjYwNS40ODEwNCwibmJmIjoxNzU4MjkyNjA1LjQ4MTA0MiwiZXhwIjoxNzU5NTg4NjA1LjQ2OTI2MSwic3ViIjoiMSIsInNjb3BlcyI6W119.BwmCo
M_bnzI9jkyiXzAvsYa7uasfn__MHc3nbLdIPGxZhU2pAmEZ6YrVcBRcMR3sXV9-gZHjP62ScG_bq_e2avnvFS6Q04WwEWH38VB-Udy4f9ozrBgdHCjUcdSjNAJ
wOuq3SPzotQ4x_gleD0x3vx3FJAndHxyGUiTTHPTfVnKhIV6m5veKYkDjJV7HcTMoIhcR7quzZANREUrwztzPP_uXfN61a-zV76tmYO-s7wcojNA_8MH2IHrOe
d3F8UVPC59BTyTqOGcYBqpSmVSvwqU0y8pA1O1RX5T2aZileeTAp_Ee1QUASvADe43zm-_3tvNKOr3TCqng3Tncpwv5fR5lO0Oh3a29hVdRIXX378HFMMaTKm4
BRwGuDng_h8gIgTGQdxINjVdeu8VDyRSaPsZCDAXSux933ZcfYXK7T2oxwu83N_RN_c68Nw-G55skPKHW_rvAlF3uPC-De0O3Pbr_dKV1k5QLBshdem-OEvwP2
FDwop_NO2qjSTZUMwr0winY2L6Wv39mP0CThoKEuTpqS2wOUEkx3_xw-OuT55VUhUZXwmRmfwmNaith_EezyKRvsOvpq95KLVwckZhFV5geQWsd6hI8lVE4tvbeWjkLlqLN2xZrzx1m4t5te2tq23b0gScOy-Dic1lMbycYidhkbxg4qD_ZupiXrecBplo